"""empty message

Revision ID: 359f9cc7e242
Revises: eb8f6177afc8
Create Date: 2023-05-08 08:36:24.592481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359f9cc7e242'
down_revision = 'eb8f6177afc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###
